apiVersion: addons.sigs.k8s.io/v1alpha1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: nomos
  git:
    syncRepo: git@github.com:ggalloro/nomos-acme-corp.git
    secretType: ssh
    policyDir: "config-root"
